# Version: 0.1a2
---

- name: 1/2-increase-fs-with-volume-resize
  hosts: localhost
  connection: local
  become: True

  tasks:

    - name: Install boto package
      pip:
        name: boto

    - name: Modify volume
      shell: aws ec2 modify-volume --volume-id {{volume_id}} --size 2

- name: 2/2-increase-fs-with-volume-resize
  hosts: aws-rhel
  remote_user: ec2-user
  become: True

  tasks:

    - name: Reread partition table
      shell: blockdev --rereadpt /dev/xvdg

    - name: Resize physical volume
      shell: pvresize /dev/xvdg

    - name: Extend logical volume
      shell: lvextend -r -l +100%FREE /dev/0001vg/0001lv
