# Version: 0.1a1
---

- name: increase-fs-with-volume-resize
  hosts: aws-rhel
  remote_user: ec2-user
  become: True

  tasks:

    - name: Reread partition table
      shell: blockdev --rereadpt /dev/xvdf

    - name: Resize physical volume
      shell: pvresize /dev/xvdf

    - name: Extend logical volume
      shell: lvextend -r -l +100%FREE /dev/0001vg/0001lv
