# Version: 0.1a3
---

- name: remove-pv
  hosts: red-hat
  remote_user: ec2-user

  tasks:

    - name: Unmount FS
      become: True
      mount:
        path: /test
        state: unmounted

    - name: Remove LV
      become: True
      shell: lvremove -f /dev/0001vg/0001lv

    - name: Reduce VG
      become: True
      shell: vgreduce 0001vg /dev/xvdg

    - name: Remove PV
      become: True
      shell: pvremove /dev/xvdg

    - name: Create LV
      become: True
      shell: lvcreate -l 100%FREE -n 0001lv 0001vg

    - name: Make FS
      become: True
      shell: mkfs.ext4 /dev/0001vg/0001lv

    - name: Mount FS
      become: True
      shell: mount -a
