# Version: 0.1a6
---

- name: increase-fs-with-new-volume
  hosts: localhost
  connection: local

  tasks:

    - name: Install boto package
      become: True
      pip:
        name: boto

    - name: Create volume and save output to `output` var
      become: True
      shell: aws ec2 create-volume --volume-type gp2 --size 1 --region eu-west-1 --availability-zone eu-west-1b
      register: output

    - name: Write `output` var to `/tmp/data.json` file
      shell: echo "{{ output.stdout_lines | to_json }}" > /tmp/data.json

    - name: Get value of `VolumeId`
      shell: python3 -c 'import json; file = open("/tmp/data.json", "r"); data=file.read().replace(",,",",").replace("{,", "{").replace(", }"," }"); file.close(); print(json.loads(data)[0]["VolumeId"])'
      register: output1

    - name: Save `VolumeId`
      shell: echo "{{ output1.stdout }}" > /tmp/volume_id

    - name: Get value of `Size`
      shell: python3 -c 'import json; file = open("/tmp/data.json", "r"); data=file.read().replace(",,",",").replace("{,", "{").replace(", }"," }"); file.close(); print(json.loads(data)[0]["Size"])'
      register: output2

    - name: Save `Size`
      shell: echo "{{ output2.stdout }}" > /tmp/size

    - name: Wait 10 seconds
      shell: sleep 10

    - name: Attach volume
      become: True
      shell: aws ec2 attach-volume --volume-id {{ output1.stdout }} --instance-id i-0ac94e664c5f2afc7 --device /dev/sdg

    - name: Delete `/tmp/data.json` file
      file:
        state: absent
        path: /tmp/data.json

    - name: Wait 10 seconds
      shell: sleep 10

    - name: Create PV
      become: True
      shell: pvcreate /dev/xvdg

    - name: Extend VG
      become: True
      shell: vgextend 0001vg /dev/xvdg

    - name: Extend LV
      become: True
      shell: lvextend -r -l +100%FREE /dev/0001vg/0001lv
