# Version: 0.1a5
---

- name: increase-fs-with-volume-resize
  hosts: localhost
  connection: local

  tasks:

    - name: Install boto package
      become: True
      pip:
        name: boto

    - name: Get `VolumeId`
      shell: cat /tmp/volume_id
      register: output1

    - name: Get current `Size` and calc new
      shell: expr `cat /tmp/size` + 1
      register: output2

    - name: Modify volume
      become: True
      shell: aws ec2 modify-volume --volume-id {{ output1.stdout }} --size {{ output2.stdout }}

    - name: Update `Size`
      become: True
      shell: echo "{{ output2.stdout }}" > /tmp/size

    - name: Wait 10 seconds
      shell: sleep 10

    - name: Reread partition table
      become: True
      shell: blockdev --rereadpt /dev/xvdg

    - name: Resize physical volume
      become: True
      shell: pvresize /dev/xvdg

    - name: Extend logical volume
      become: True
      shell: lvextend -r -l +100%FREE /dev/0001vg/0001lv
