# Version: 0.1a3
---

- name: remove-volume
  hosts: localhost
  connection: local

  tasks:

    - name: Unmount FS
      become: True
      mount:
        path: /test
        state: unmounted

    - name: Remove LV
      become: True
      shell: lvremove -f /dev/0001vg/0001lv

    - name: Reduce VG
      become: True
      shell: vgreduce 0001vg /dev/xvdg

    - name: Remove PV
      become: True
      shell: pvremove /dev/xvdg

    - name: Create LV
      become: True
      shell: lvcreate -l 100%FREE -n 0001lv 0001vg

    - name: Make FS
      become: True
      shell: mkfs.ext4 /dev/0001vg/0001lv

    - name: Mount FS
      become: True
      shell: mount -a

    - name: Get `VolumeId`
      shell: cat /tmp/volume_id
      register: output

    - name: Detach volume
      become: True
      shell: aws ec2 detach-volume --volume-id {{ output.stdout }}

    - name: Wait 10 seconds
      shell: sleep 10

    - name: Delete volume
      become: True
      shell: aws ec2 delete-volume --volume-id {{ output.stdout }}
