# Version: 0.1a3
---

- name: increase-tablespace
  hosts: localhost
  connection: local

  tasks:

    - name: Add Oracle DB datafile
      environment:
        LD_LIBRARY_PATH: /usr/lib/oracle/12.2/client64/lib
      oracle_tablespace:
        hostname={{ host }}
        service_name={{ db_name }}
        tablespace={{ tablespace_name }}
        user={{ db_user }}
        password={{ db_passwd }}
        free_mb={{ free_mb }}
        size={{ size }}
        nextsize={{ next_size }}
        maxsize={{ max_size }}
        state=free
